[build]
publish = "out"
command = "npm run build"

[build.environment]
NODE_VERSION = "22"

[[redirects]]
from = "/v2/*"
to = "https://api.upak.space/v2/:splat"
status = 200
force = true

# Настройки для SSG
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
